// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEghQcm90b2NvbCozCg1Sb29tU3RhdGVUeXBlEggKBFdB",
            "SVQQABILCgdQUkVQQVJFEAESCwoHSU5BR0FNRRACKkkKCk9iamVjdFR5cGUS",
            "CQoFVE9XRVIQABIKCgZQTEFZRVIQARILCgdNT05TVEVSEAISDgoKUFJPSkVD",
            "VElMRRADEgcKA0VOVhAEKjIKEU9CSkVDVF9TVEFURV9UWVBFEggKBElETEUQ",
            "ABIICgRNT1ZFEAESCQoFU0tJTEwQAioyCghDYXJkVHlwZRIQCgxBVFRBQ0tf",
            "VE9XRVIQABIUChBTVFJfQVRUQUNLX1RPV0VSEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.RoomStateType), typeof(global::Protocol.ObjectType), typeof(global::Protocol.OBJECT_STATE_TYPE), typeof(global::Protocol.CardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///변경 주의(클라 의존성)
  /// </summary>
  public enum RoomStateType {
    [pbr::OriginalName("WAIT")] Wait = 0,
    [pbr::OriginalName("PREPARE")] Prepare = 1,
    [pbr::OriginalName("INAGAME")] Inagame = 2,
  }

  public enum ObjectType {
    [pbr::OriginalName("TOWER")] Tower = 0,
    [pbr::OriginalName("PLAYER")] Player = 1,
    [pbr::OriginalName("MONSTER")] Monster = 2,
    [pbr::OriginalName("PROJECTILE")] Projectile = 3,
    [pbr::OriginalName("ENV")] Env = 4,
  }

  public enum OBJECT_STATE_TYPE {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("SKILL")] Skill = 2,
  }

  public enum CardType {
    [pbr::OriginalName("ATTACK_TOWER")] AttackTower = 0,
    /// <summary>
    /// 추가해야됨
    /// </summary>
    [pbr::OriginalName("STR_ATTACK_TOWER")] StrAttackTower = 1,
  }

  #endregion

}

#endregion Designer generated code
